### ISSUE TITLE
code editor breaking in rosmod hfsm

### ISSUE THREAD

**Issue by DWatkins** [finger563/webgme-hfsm#88]
```
q.js:161 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at https://rosmod.vadl.vanderbilt.edu/extlib/node_modules/webgme-codeeditor/src/visualizers/widgets/CodeEditor/CodeEditorWidget.js:842:66
    at Array.sort (native)
    at FancytreeNode.sortChildren (https://rosmod.vadl.vanderbilt.edu/bower_components/jquery.fancytree/dist/jquery.fancytree-all.js:1759:6)
    at FancytreeNode.sortChildren (https://rosmod.vadl.vanderbilt.edu/bower_components/jquery.fancytree/dist/jquery.fancytree-all.js:1763:12)
    at FancytreeNode.sortChildren (https://rosmod.vadl.vanderbilt.edu/bower_components/jquery.fancytree/dist/jquery.fancytree-all.js:1763:12)
    at FancytreeNode.sortChildren (https://rosmod.vadl.vanderbilt.edu/bower_components/jquery.fancytree/dist/jquery.fancytree-all.js:1763:12)
    at FancytreeNode.sortChildren (https://rosmod.vadl.vanderbilt.edu/bower_components/jquery.fancytree/dist/jquery.fancytree-all.js:1763:12)
    at FancytreeNode.sortChildren (https://rosmod.vadl.vanderbilt.edu/bower_components/jquery.fancytree/dist/jquery.fancytree-all.js:1763:12)
    at CodeEditorWidget.createNode (https://rosmod.vadl.vanderbilt.edu/extlib/node_modules/webgme-codeeditor/src/visualizers/widgets/CodeEditor/CodeEditorWidget.js:839:43)
    at CodeEditorWidget.addNode (https://rosmod.vadl.vanderbilt.edu/extlib/node_modules/webgme-codeeditor/src/visualizers/widgets/CodeEditor/CodeEditorWidget.js:867:22)
```

relevant code snippet
```node
self._fancyTree.getRootNode().sortChildren(
                function(a, b) {
                    var x = (a.isFolder() ? "1" : "0") + a.title.toLowerCase(),
                        y = (b.isFolder() ? "1" : "0") + b.title.toLowerCase();
                    return x === y ? 0 : x > y ? 1 : -1;
                },
                true); // true for sorting deeply
```

**Comment by DWatkins** [comment]
wrong repo :P
